version: '3.8'

services:

  postgredb:
    image: postgres
    container_name: postgresql_db
    ports:
      - "5432:5432"
    volumes:
      - ./:/postgresql:/var/lib/postgresql/data
    networks:
      - backend-network
    env_file:
      - envs/our_project.env
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
      - PGDATA=/var/lib/postgresql/data/pgdata
    restart: on-failure

  backend:
    depends_on:
      - postgredb
    image: backend-softuni:v01
    build:
      dockerfile: Dockerfile
    container_name: backend-softuni
    ports:
      - "8000:80"
    networks:
      - backend-network
      - frontend-network
    env_file:
      - ./envs/our_project.env
    restart: on-failure

  frontend:
    depends_on:
      - backend
    image: frontend-softuni:v01
    build:
      dockerfile: frontend/Dockerfile
    ports:
      - "3000:81"
    container_name: frontend-softuni
    networks:
      - frontend-network
    restart: on-failure


volumes:
  postgresql:
    name: postgresql

networks:
  frontend-network:
    name: frontend-network
  backend-network:
    name: backend-network