# Generated by Django 4.2.10 on 2024-03-22 10:59

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='picture',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Voter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voted_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voted_users', to='backend.rating')),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voters', to='backend.user')),
            ],
        ),
        migrations.AddField(
            model_name='rating',
            name='user',
            field=models.ManyToManyField(related_name='ratings', through='backend.Voter', to='backend.user'),
        ),
    ]
