# Generated by Django 4.2.10 on 2024-03-22 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='picture',
            field=models.TextField(blank=True, null=True),
        ),
    ]
