# Generated by Django 4.2.10 on 2024-03-02 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.CharField(blank=True, choices=[('BG01', 'Blagoevgrad'), ('BG02', 'Burgas'), ('BG03', 'Varna'), ('BG04', 'Veliko Tarnovo'), ('BG05', 'Vidin'), ('BG06', 'Vratsa'), ('BG07', 'Gabrovo'), ('BG08', 'Dobrich'), ('BG09', 'Kardzhali'), ('BG10', 'Kyustendil'), ('BG11', 'Lovech'), ('BG12', 'Montana'), ('BG13', 'Pazardzhik'), ('BG14', 'Pernik'), ('BG15', 'Pleven'), ('BG16', 'Plovdiv'), ('BG17', 'Razgrad'), ('BG18', 'Ruse'), ('BG19', 'Silistra'), ('BG20', 'Sliven'), ('BG21', 'Smolyan'), ('BG22', 'Grad Sofiya'), ('BG23', 'Sofia'), ('BG24', 'Stara Zagora'), ('BG25', 'Targovishte'), ('BG26', 'Haskovo'), ('BG27', 'Shumen'), ('BG28', 'Yambol')], max_length=120, null=True),
        ),
    ]
