# Generated by Django 4.2.10 on 2024-03-22 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_voter_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='voter',
            name='id_voted_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='id_voted_user', to='backend.user'),
            preserve_default=False,
        ),
    ]
