def information_cities():
    return (
        ('BG01', 'Blagoevgrad'),
        ('BG02', 'Burgas'),
        ('BG03', 'Varna'),
        ('BG04', 'Veliko Tarnovo'),
        ('BG05', 'Vidin'),
        ('BG06', 'Vratsa'),
        ('BG07', 'Gabrovo'),
        ('BG08', 'Dobrich'),
        ('BG09', 'Kardzhali'),
        ('BG10', 'Kyustendil'),
        ('BG11', 'Lovech'),
        ('BG12', 'Montana'),
        ('BG13', 'Pazardzhik'),
        ('BG14', 'Pernik'),
        ('BG15', 'Pleven'),
        ('BG16', 'Plovdiv'),
        ('BG17', 'Razgrad'),
        ('BG18', 'Ruse'),
        ('BG19', 'Silistra'),
        ('BG20', 'Sliven'),
        ('BG21', 'Smolyan'),
        ('BG22', 'Grad Sofiya'),
        ('BG23', 'Sofia'),
        ('BG24', 'Stara Zagora'),
        ('BG25', 'Targovishte'),
        ('BG26', 'Haskovo'),
        ('BG27', 'Shumen'),
        ('BG28', 'Yambol'),
    )