name: CI/CD workflow for FrontEnd

on:
  push:
    branches:
      - DevOps
    paths:
      - 'frontend/**'
      - '.github/workflows/pipeline_frontend.yml'

  pull_request:
    branches:
      - DevOps
    paths:
      - 'frontend/**'
      - '.github/workflows/pipeline_frontend.yml'


jobs:
  build-frontend:

    runs-on: ubuntu-latest

    steps:
      - name: CheckoutCode
        working-directory: frontend/
        uses: actions/checkout@v3
      - name: Use Node.js 21.x
        working-directory: frontend/
        uses: actions/setup-node@v3
        with:
          node-version: 21.x
          cache: "npm"
      - name: Build & install dependencies
        working-directory: frontend/
        run: npm install
      - name: Run WebApplication
        working-directory: frontend/
        run: npm run dev


  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to production in Render.com
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ secrets.FRONTEND_SERVICE_ID }}
          api-key: ${{ secrets.MY_RENDER_API_KEY }}
    needs: build-frontend
