name: CI/CD workflow for BackEnd

on:
  push:
    branches: [ "DevOps" ]
  pull_request:
    branches: [ "DevOps" ]
env:
  DB_NAME: ${{ secrets.DB_NAME }}
  DB_USER: ${{ secrets.DB_USER }}
  DB_PASSWORD: ${{ secrets.DB_PASSWORD }}


jobs:
  build-and-test-backend:

    runs-on: ubuntu-latest

    steps:
      - name: Setup PostgreSQL for build & tests
        uses: Harmon758/postgresql-action@v1.0.0
        with:
          postgresql version: 12
          postgresql db:
            POSTGRES_DB=${{ secrets.DB_NAME }}
          postgresql user:
            POSTGRES_USER=${{ secrets.DB_USER }}
          postgresql password:
            POSTGRES_PASSWORD=${{ secrets.DB_PASSWORD }}

      - name: CheckoutCode
        uses: actions/checkout@v3
      - name: Set up Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: 3.11
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Migrate to DB to run tests
        run: |
          python manage.py makemigrations
          python manage.py migrate
      - name: Run Tests
        run: |
          coverage run manage.py test
          coverage report --omit=tests/*

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to production in Render.com
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ secrets.MY_RENDER_SERVICE_ID }}
          api-key: ${{ secrets.MY_RENDER_API_KEY }}
    needs: build-test
