name: CI/CD workflow for BackEnd

on:
  push:
    branches:
      - DevOps
    paths-ignore:
      - 'frontend/**'
  pull_request:
    branches:
      - DevOps
    paths-ignore:
      - 'frontend/**'

env:
  SECRET_KEY: 'django-insecure-a6^74w0ypqs9ekp#yut_+)3higc9$48#s1e)_*4lmls7#1cxza'
  DEBUG: 0
  ALLOWED_HOSTS: 127.0.0.1 localhost host.docker.internal https://softuniada-project-backend.onrender.com
  DB_NAME: softuni_project
  DB_USER: AdminUserDB
  DB_PASSWORD: Stro0ng@Passw0rd
  DB_HOST: ${{ job.services.postgres.host }}
  DB_PORT: ${{ job.services.postgres.ports }}
  CORS_ALLOWED_ORIGINS: http://localhost:3000 https://soft-vrlm.vercel.app

jobs:
  build-and-test-backend:

    runs-on: ubuntu-latest

    steps:
      - name: Setup PostgreSQL for build & tests
        uses: Harmon758/postgresql-action@v1.0.0
        with:
          postgresql version: 12
          postgresql db:
            POSTGRES_DB=${{ env.DB_NAME }}
          postgresql user:
            POSTGRES_USER=${{ env.DB_USER }}
          postgresql password:
            POSTGRES_PASSWORD=${{ env.DB_PASSWORD }}
      - name: Wait DB 60 seconds
        run: sleep 60
      - name: CheckoutCode
        uses: actions/checkout@v3
      - name: Set up Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: 3.11
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Migrate to DB to run tests
        run: |
          python manage.py makemigrations
          python manage.py migrate
      - name: Run Tests
        run: |
          coverage run manage.py test
          coverage report --omit=tests/*

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to production in Render.com
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ secrets.MY_RENDER_SERVICE_ID }}
          api-key: ${{ secrets.MY_RENDER_API_KEY }}
    needs: build-and-test-backend
